#!/usr/bin/env python3
"""
step5d_duplicate_resolution.py — Duplicate Resolution Engine
=============================================================
CDCI P&ID Pipeline — Step 5D

Type: PROGRAMMATIC — No Gemini, No Claude

Purpose
-------
Remove duplicate detections generated by SAHI overlapping patches.
The same valve or instrument will be detected 2–4 times by adjacent patches.

Resolution algorithms (per Gemini Multimodal Strategy doc)
-----------------------------------------------------------
  1. Bounding Box IoU (Intersection over Union) — primary signal
  2. Spatial Distance between symbol centers — secondary
  3. Tag Text Similarity — fuzzy string match (Levenshtein-like)
  4. Spatial Mask Merging (SMM) — merge fragmented detections along
     thin engineering diagram lines where standard NMS fails

Output per candidate
---------------------
  {
    "candidate_id":    "",
    "duplicate_status": "PRIMARY|MERGED|DISCARDED"
  }

Final output schema (Step 5 complete)
--------------------------------------
  {
    candidate_id, tag_text, symbol_name, symbol_category,
    connected_pipe, connected_equipment,
    sow_status, validation_status, duplicate_status
  }

Usage
-----
  python step5d_duplicate_resolution.py \\
      --validated output/step5c_validated.json --out output/

  python step5d_duplicate_resolution.py \\
      --context output/drawing_context.json
"""

import argparse
import json
import logging
import math
import re
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

# ── Deduplication thresholds ───────────────────────────────────────────────────
IOU_MERGE_THRESHOLD      = 0.20   # IoU ≥ 0.20 → likely same detection
DIST_MERGE_THRESHOLD_PX  = 200    # center distance ≤ 200px → likely same
TAG_SIM_THRESHOLD        = 0.80   # tag text similarity ≥ 80% → same tag
SMM_OVERLAP_THRESHOLD    = 0.10   # SMM: minimum overlap fraction for merging
EXACT_TAG_MERGE_DIST_PX  = 400    # EXACT same tag text within 400px → ALWAYS merge


# ═══════════════════════════════════════════════════════════════════════════════
# Geometry utilities
# ═══════════════════════════════════════════════════════════════════════════════

def bbox_area(b: dict) -> float:
    w = max(0, b.get("x2", 0) - b.get("x1", 0))
    h = max(0, b.get("y2", 0) - b.get("y1", 0))
    return float(w * h)


def bbox_iou(a: dict, b: dict) -> float:
    """Intersection over Union for two bboxes."""
    ix1 = max(a.get("x1", 0), b.get("x1", 0))
    iy1 = max(a.get("y1", 0), b.get("y1", 0))
    ix2 = min(a.get("x2", 0), b.get("x2", 0))
    iy2 = min(a.get("y2", 0), b.get("y2", 0))

    inter_w = max(0, ix2 - ix1)
    inter_h = max(0, iy2 - iy1)
    inter   = float(inter_w * inter_h)
    if inter == 0:
        return 0.0

    union = bbox_area(a) + bbox_area(b) - inter
    return inter / union if union > 0 else 0.0


def bbox_center(b: dict) -> tuple[float, float]:
    return (
        (b.get("x1", 0) + b.get("x2", 0)) / 2,
        (b.get("y1", 0) + b.get("y2", 0)) / 2,
    )


def center_dist(a: dict, b: dict) -> float:
    ax, ay = bbox_center(a)
    bx, by = bbox_center(b)
    return math.sqrt((ax - bx) ** 2 + (ay - by) ** 2)


def merge_bboxes(boxes: list[dict]) -> dict:
    """Merge multiple bboxes into a single containing bbox."""
    if not boxes:
        return {}
    return {
        "x1": min(b.get("x1", 0) for b in boxes),
        "y1": min(b.get("y1", 0) for b in boxes),
        "x2": max(b.get("x2", 0) for b in boxes),
        "y2": max(b.get("y2", 0) for b in boxes),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Tag similarity
# ═══════════════════════════════════════════════════════════════════════════════

def _normalise_tag(tag: str) -> str:
    """Normalise tag for comparison: uppercase, collapse spaces/hyphens."""
    return re.sub(r'[\s\-\.]+', '', str(tag or "").upper().strip())


def tag_similarity(tag_a: str, tag_b: str) -> float:
    """
    Fast tag similarity:
      1.0 → identical after normalisation
      0.9 → differ only in OCR-common confusion (0/O, 1/I, 5/S, 8/B)
      0.7 → share common prefix of ≥ 4 chars
      0.0 → completely different
    """
    a = _normalise_tag(tag_a)
    b = _normalise_tag(tag_b)

    if not a or not b:
        return 0.0
    if a == b:
        return 1.0

    # OCR confusion substitutions
    CONFUSABLES = str.maketrans("0O1I5S8B", "OOII5S8B")
    if a.translate(CONFUSABLES) == b.translate(CONFUSABLES):
        return 0.9

    # Common prefix
    prefix_len = 0
    for ca, cb in zip(a, b):
        if ca == cb:
            prefix_len += 1
        else:
            break
    min_len = min(len(a), len(b))
    if min_len > 0 and prefix_len >= 4:
        return 0.7 * prefix_len / min_len

    # Length-weighted character overlap
    common = sum(1 for ca, cb in zip(a, b) if ca == cb)
    return 2 * common / (len(a) + len(b)) if (len(a) + len(b)) > 0 else 0.0


# ═══════════════════════════════════════════════════════════════════════════════
# Spatial Mask Merging (SMM)
# ═══════════════════════════════════════════════════════════════════════════════

def smm_should_merge(a: dict, b: dict) -> bool:
    """
    SMM: merge two candidates if their bboxes overlap significantly
    OR if one partially overlaps the other AND they share the same tag text
    (fragmented detection along thin lines — classic SAHI failure mode).

    Per Gemini Strategy doc: "SMM integrates pixel-level overlap and
    boundary distance metrics to merge fragmented detections."
    """
    iou  = bbox_iou(a.get("symbol_bbox", {}), b.get("symbol_bbox", {}))
    dist = center_dist(a.get("symbol_bbox", {}), b.get("symbol_bbox", {}))
    tsim = tag_similarity(a.get("tag_text", ""), b.get("tag_text", ""))

    # Rule 0: EXACT same tag text within 400px → ALWAYS merge (highest priority)
    # This catches SAHI duplicates where Gemini returns different bboxes
    # for the same physical tag from adjacent patches
    tag_a = _normalise_tag(a.get("tag_text", ""))
    tag_b = _normalise_tag(b.get("tag_text", ""))
    if tag_a and tag_b and tag_a == tag_b and dist <= EXACT_TAG_MERGE_DIST_PX:
        return True

    # Rule 1: Strong IoU overlap (any tags)
    if iou >= IOU_MERGE_THRESHOLD:
        return True

    # Rule 2: Moderate proximity + similar tag text
    if dist <= DIST_MERGE_THRESHOLD_PX and tsim >= TAG_SIM_THRESHOLD:
        return True

    # SMM: partial overlap + tag text match (fragmented detection)
    ba = a.get("symbol_bbox", {})
    bb = b.get("symbol_bbox", {})
    area_a = bbox_area(ba)
    area_b = bbox_area(bb)
    if area_a > 0 and area_b > 0:
        ix1 = max(ba.get("x1",0), bb.get("x1",0))
        iy1 = max(ba.get("y1",0), bb.get("y1",0))
        ix2 = min(ba.get("x2",0), bb.get("x2",0))
        iy2 = min(ba.get("y2",0), bb.get("y2",0))
        inter = max(0, ix2 - ix1) * max(0, iy2 - iy1)
        overlap_a = inter / area_a
        overlap_b = inter / area_b
        if (max(overlap_a, overlap_b) >= SMM_OVERLAP_THRESHOLD
                and tsim >= 0.7):
            return True

    return False


# ═══════════════════════════════════════════════════════════════════════════════
# Main deduplication
# ═══════════════════════════════════════════════════════════════════════════════

def resolve_duplicates(candidates: list[dict]) -> list[dict]:
    """
    Union-Find based duplicate resolution with SMM.

    Algorithm:
      1. For each pair of candidates, run smm_should_merge()
      2. Group merged candidates using Union-Find
      3. Per group: select PRIMARY (highest combined confidence)
         mark rest as MERGED or DISCARDED
      4. Merge bboxes of DISCARDED into PRIMARY's bbox
    """
    n = len(candidates)
    if n == 0:
        return []

    # Union-Find
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        px, py = find(x), find(y)
        if px != py:
            parent[px] = py

    log.info("Running SMM deduplication on %d candidates...", n)

    merge_count = 0
    for i in range(n):
        for j in range(i + 1, n):
            if smm_should_merge(candidates[i], candidates[j]):
                union(i, j)
                merge_count += 1

    log.info("SMM: found %d merge pairs → building groups", merge_count)

    # Group by root
    from collections import defaultdict
    groups: dict[int, list[int]] = defaultdict(list)
    for i in range(n):
        groups[find(i)].append(i)

    results = []
    primary_count   = 0
    merged_count    = 0
    discarded_count = 0

    for root, members in groups.items():
        if len(members) == 1:
            c = {**candidates[members[0]]}
            c["duplicate_status"] = "PRIMARY"
            c["merged_from"]      = []
            results.append(c)
            primary_count += 1
            continue

        # Multiple candidates in group → select PRIMARY
        def _score(idx: int) -> float:
            cand = candidates[idx]
            return (
                float(cand.get("vision_confidence") or 0) * 0.4 +
                float(cand.get("ocr_confidence")    or 0) * 0.3 +
                float(cand.get("association_confidence") or 0) * 0.2 +
                (0.1 if cand.get("validation_status") == "PASS" else 0)
            )

        members_sorted = sorted(members, key=_score, reverse=True)
        primary_idx    = members_sorted[0]
        merged_idxs    = members_sorted[1:]

        primary = {**candidates[primary_idx]}
        primary["duplicate_status"] = "PRIMARY"

        # Merge bboxes of all group members into PRIMARY
        all_sym_bboxes = [candidates[m].get("symbol_bbox", {}) for m in members]
        primary["symbol_bbox"]  = merge_bboxes(all_sym_bboxes)
        primary["merged_from"]  = [candidates[m]["candidate_id"] for m in merged_idxs]
        primary["merged_count"] = len(merged_idxs)

        # Use highest OCR-confidence tag text
        best_tag  = primary.get("tag_text", "")
        best_conf = float(primary.get("ocr_confidence") or 0)
        for m in merged_idxs:
            c = candidates[m]
            c_conf = float(c.get("ocr_confidence") or 0)
            c_tag  = str(c.get("tag_text") or "")
            if c_conf > best_conf and c_tag:
                best_tag  = c_tag
                best_conf = c_conf
        primary["tag_text"]       = best_tag
        primary["ocr_confidence"] = round(best_conf, 3)

        results.append(primary)
        primary_count += 1

        for m in merged_idxs:
            merged = {**candidates[m]}
            merged["duplicate_status"] = "DISCARDED"
            merged["merged_into"]      = candidates[primary_idx]["candidate_id"]
            results.append(merged)
            discarded_count += 1

    log.info("Deduplication complete: %d PRIMARY | %d DISCARDED (from %d total)",
             primary_count, discarded_count, n)
    return results


# ═══════════════════════════════════════════════════════════════════════════════
# Final output builder — combines all Step 5 data into the final schema
# ═══════════════════════════════════════════════════════════════════════════════

def build_final_step5_output(deduped: list[dict]) -> list[dict]:
    """
    Produce the final Step 5 output schema as defined in the spec.
    Only PRIMARY records are included (DISCARDED are dropped).
    """
    final = []
    for cand in deduped:
        if cand.get("duplicate_status") != "PRIMARY":
            continue
        final.append({
            "candidate_id":       cand.get("candidate_id", ""),
            "tag_text":           cand.get("tag_text", ""),
            "symbol_name":        cand.get("symbol_name", ""),
            "symbol_category":    cand.get("symbol_category", ""),
            "symbol_bbox":        cand.get("symbol_bbox", {}),
            "tag_bbox":           cand.get("tag_bbox", {}),
            "connected_pipe":     cand.get("connected_pipe", ""),
            "connected_equipment":cand.get("connected_equipment", ""),
            "spatial_relationship":cand.get("spatial_relationship", ""),
            "sow_status":         cand.get("sow_status", "UNSPECIFIED"),
            "sow_reason":         cand.get("sow_reason", ""),
            "validation_status":  cand.get("validation_status", "WARN"),
            "validation_reason":  cand.get("validation_reason", ""),
            "duplicate_status":   "PRIMARY",
            "merged_count":       cand.get("merged_count", 0),
            "ocr_confidence":     cand.get("ocr_confidence", 0.0),
            "vision_confidence":  cand.get("vision_confidence", 0.0),
            "association_confidence": cand.get("association_confidence", 0.0),
            "patch_id":           cand.get("patch_id"),
            "scope_type":         cand.get("scope_type", "FULL_DRAWING"),
        })
    return final


# ═══════════════════════════════════════════════════════════════════════════════
# Main pipeline
# ═══════════════════════════════════════════════════════════════════════════════

def run_duplicate_resolution(
    validated_path: str,
    out_dir: str,
) -> list[dict]:

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    with open(validated_path) as f:
        data = json.load(f)
    candidates = data.get("validated_candidates",
                 data.get("enriched_candidates",
                 data.get("candidates", [])))
    log.info("Loaded %d validated candidates for deduplication", len(candidates))

    # Run SMM deduplication
    deduped = resolve_duplicates(candidates)

    # Build final Step 5 output
    final   = build_final_step5_output(deduped)

    primary_count   = sum(1 for c in deduped if c.get("duplicate_status") == "PRIMARY")
    discarded_count = sum(1 for c in deduped if c.get("duplicate_status") == "DISCARDED")

    val_summary = {"PASS": 0, "WARN": 0, "FAIL": 0}
    for c in final:
        s = c.get("validation_status", "WARN")
        val_summary[s] = val_summary.get(s, 0) + 1

    sow_summary = {"IN_SCOPE": 0, "OUT_OF_SCOPE": 0, "UNSPECIFIED": 0}
    for c in final:
        s = c.get("sow_status", "UNSPECIFIED")
        sow_summary[s] = sow_summary.get(s, 0) + 1

    # Write step5d_deduped.json (full with DISCARDED)
    deduped_path = str(out / "step5d_deduped.json")
    with open(deduped_path, "w") as f:
        json.dump({
            "version":          "v1",
            "total_input":      len(candidates),
            "primary_count":    primary_count,
            "discarded_count":  discarded_count,
            "all_records":      deduped,
        }, f, indent=2)
    log.info("✓ step5d_deduped.json → %s", deduped_path)

    # Write step5_final_output.json (PRIMARY only — feeds Steps 7 & 8)
    final_path = str(out / "step5_final_output.json")
    with open(final_path, "w") as f:
        json.dump({
            "version":            "v1",
            "step":               "5D_FINAL",
            "total_candidates":   len(final),
            "validation_summary": val_summary,
            "sow_summary":        sow_summary,
            "dedup_summary": {
                "input":     len(candidates),
                "primary":   primary_count,
                "discarded": discarded_count,
                "reduction": f"{discarded_count/max(len(candidates),1)*100:.1f}%",
            },
            "candidates":         final,
        }, f, indent=2)
    log.info("✓ step5_final_output.json (%d final candidates) → %s",
             len(final), final_path)
    return final


# ═══════════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Step 5D: Duplicate Resolution Engine (SMM)")
    parser.add_argument("--validated", help="step5c_validated.json")
    parser.add_argument("--context",   help="drawing_context.json")
    parser.add_argument("--out",       default="output")
    args = parser.parse_args()

    validated_path = args.validated
    if args.context:
        validated_path = validated_path or str(Path(args.out) / "step5c_validated.json")

    validated_path = validated_path or str(Path(args.out) / "step5c_validated.json")

    final = run_duplicate_resolution(validated_path, args.out)

    val = {"PASS": 0, "WARN": 0, "FAIL": 0}
    sow = {"IN_SCOPE": 0, "OUT_OF_SCOPE": 0, "UNSPECIFIED": 0}
    for c in final:
        val[c.get("validation_status","WARN")] = val.get(c.get("validation_status","WARN"),0)+1
        sow[c.get("sow_status","UNSPECIFIED")] = sow.get(c.get("sow_status","UNSPECIFIED"),0)+1

    print(f"\n=== Step 5D Complete — Final Step 5 Output ===")
    print(f"  Final candidates  : {len(final)}")
    print(f"\n  Validation:")
    for k, v in val.items():
        print(f"    {k:<10} {v:>4}")
    print(f"\n  SOW scope:")
    for k, v in sow.items():
        print(f"    {k:<20} {v:>4}")
    print(f"\n  Output: {args.out}/step5_final_output.json")
    print(f"          {args.out}/step5d_deduped.json")


if __name__ == "__main__":
    main()